data_dir: /data/private/wangxin/raw
factor_freq: 10  # 10-minute bars
n_train: 1000
n_valid: 30
dropout: 0.3
seed: 43
universe: euniv_largemid
trading_slot: '0930'
agg: last

log_dir: log_0930
checkpoint_dir: checkpoint_0930

rolling_month_gap: 1

x_slots: [
# '0940', '0950', '1000',
#           '1010', '1020', '1030',
          # '1040', '1050', '1100',
          # '1110', '1120', '1130',
          '1310', '1320', '1330',
          '1340', '1350', '1400',
          '1410', '1420', '1430',
          '1440', '1450', '1500']

# 0931 of next day
y_slot: '0931'
y_lag: 1  # 0 or 1

returns: [1, 2, 5]  # 1D, 2D, 5D returns for training.
