

data_dir: /data/private/wangxin/raw
factor_freq: 10 # 10-minute bars
n_train: 1000
n_valid: 30
dropout: 0.3
seed: 43
universe: euniv_largemid
trading_slot: '1400'
agg: last

log_dir: log_1400
checkpoint_dir: checkpoint_1400

rolling_month_gap: 1

x_slots: ['1040',
 '1050',
 '1100',
 '1110',
 '1120',
 '1130',
 '1310',
 '1320',
 '1330',
 '1340',
 '1350',
 '1400',]

y_slot: 1400
y_lag: 0

returns: [1, 2, 5] # 1D, 2D, 5D returns for training.
