target-version = "py310"
indent-width = 2
line-length = 88

[lint]
select = ["E", "F", "I"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

