name: Build Cython Wheel

on:
  push:
    branches: [ extend ]
  pull_request:
    branches: [ extend ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython wheel setuptools numpy

    - name: Install Make on Windows
      if: runner.os == 'Windows'
      run: |
        choco install make
        
    - name: Build Cython wheel
      run: |
        make build_cython

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheels_extend
        path: dist/*.whl
